name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  flutter:
    sdk: flutter
  get: 4.6.1
  http: ^0.13.4
  intl: ^0.17.0
  lottie: ^1.2.2
  sticky_headers: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/
    - assets/lotties/
    

  fonts:
    - family: UiIcons
      fonts:
        - asset: assets/fonts/UiIcons.ttf
